import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import type { Database, DatabaseTransaction } from './index.js';
import { actionRequestSchema, executionAttemptSchema, outcomeSchema, type ActionRequest, type ExecutionAttempt, type Outcome } from '@kablet/domain';
type Tx = DatabaseTransaction;
function mapActionRequest(row: Record<string, unknown>): ActionRequest { return actionRequestSchema.parse({ contractVersion: 'action-request.v1', requestId: String(row.id), organizationId: String(row.organization_id), businessId: String(row.business_id), visitorIdentityId: String(row.visitor_identity_id), sessionId: String(row.session_id), decisionId: String(row.decision_id), capabilityId: String(row.capability_id), capabilityVersion: String(row.capability_version), input: row.input, idempotencyKey: String(row.idempotency_key), requestedAt: row.created_at, status: row.status }); }
function mapExecutionAttempt(row: Record<string, unknown>): ExecutionAttempt { return executionAttemptSchema.parse({ contractVersion: 'execution-attempt.v1', executionId: String(row.id), actionRequestId: String(row.action_request_id), attemptNumber: Number(row.attempt_number), status: row.status, externalOperationId: String(row.external_operation_id), adapterRequestId: row.adapter_request_id === null ? null : String(row.adapter_request_id), failureCode: row.failure_code === null ? null : String(row.failure_code), startedAt: row.started_at, completedAt: row.completed_at }); }
async function tenant<T>(db: Database['db'], organizationId: string, businessId: string, fn: (tx: Tx) => Promise<T>, existingTx?: Tx) { const run = async (tx: Tx) => { await tx.execute(sql`select set_config('kablet.organization_id',${organizationId},true), set_config('kablet.business_id',${businessId},true)`); return fn(tx); }; return existingTx ? run(existingTx) : db.transaction(run); }
export function createActionOutcomeRepository(db: Database['db'], existingTx?: Tx) { return {
  async createRequest(input: Omit<ActionRequest, 'contractVersion'|'requestId'|'requestedAt'|'status'|'input'> & { requestId?: string; input: unknown; status?: ActionRequest['status'] }) { const request = actionRequestSchema.parse({ ...input, contractVersion: 'action-request.v1', requestId: input.requestId ?? randomUUID(), requestedAt: new Date(), status: input.status ?? 'requested' }); return tenant(db, request.organizationId, request.businessId, async tx => { const row = await tx.execute(sql`insert into action_requests (id,organization_id,business_id,visitor_identity_id,session_id,decision_id,capability_id,capability_version,input,idempotency_key,status) values (${request.requestId}::uuid,${request.organizationId}::uuid,${request.businessId}::uuid,${request.visitorIdentityId}::uuid,${request.sessionId}::uuid,${request.decisionId}::uuid,${request.capabilityId}::uuid,${request.capabilityVersion},${JSON.stringify(request.input)}::jsonb,${request.idempotencyKey},${request.status}) on conflict (organization_id,business_id,visitor_identity_id,idempotency_key) do nothing returning *`); const existing = row.rows[0] ? row.rows[0] : (await tx.execute(sql`select * from action_requests where organization_id=${request.organizationId}::uuid and business_id=${request.businessId}::uuid and visitor_identity_id=${request.visitorIdentityId}::uuid and idempotency_key=${request.idempotencyKey}`)).rows[0]; if (!existing) throw new Error('action request was not persisted'); const existingInput = JSON.stringify(existing.input); if (existingInput !== JSON.stringify(request.input) || String(existing.capability_id) !== request.capabilityId || String(existing.capability_version) !== request.capabilityVersion) throw new Error('action idempotency key conflicts with a different input'); return { request: mapActionRequest(existing as Record<string, unknown>), created: Boolean(row.rows[0]) }; }, existingTx); },
  async createAttempt(input: { organizationId:string; businessId:string; actionRequestId:string; attemptNumber:number; externalOperationId:string }, existingTx?: Tx) { return tenant(db,input.organizationId,input.businessId,async tx => { const id=randomUUID(); const row=await tx.execute(sql`insert into execution_attempts (id,organization_id,business_id,action_request_id,attempt_number,status,external_operation_id,started_at) values (${id}::uuid,${input.organizationId}::uuid,${input.businessId}::uuid,${input.actionRequestId}::uuid,${input.attemptNumber},'running',${input.externalOperationId},now()) returning *`); return mapExecutionAttempt(row.rows[0] as Record<string, unknown>); },existingTx); },
  async updateRequest(input:{organizationId:string;businessId:string;requestId:string;status:ActionRequest['status']}, existingTx?:Tx){ return tenant(db,input.organizationId,input.businessId,async tx=>{ await tx.execute(sql`update action_requests set status=${input.status} where id=${input.requestId}::uuid`); },existingTx); },
  async claimExecution(input:{organizationId:string;businessId:string;requestId:string}, existingTx?:Tx){ return tenant(db,input.organizationId,input.businessId,async tx=>{ const row=await tx.execute(sql`update action_requests set status='executing' where id=${input.requestId}::uuid and organization_id=${input.organizationId}::uuid and business_id=${input.businessId}::uuid and status='execution_pending' returning id`); return row.rows.length === 1; },existingTx); },
  async updateAttempt(input:{organizationId:string;businessId:string;executionId:string;status:ExecutionAttempt['status'];adapterRequestId:string|null;failureCode:string|null}, existingTx?:Tx){ return tenant(db,input.organizationId,input.businessId,async tx=>{ const row=await tx.execute(sql`update execution_attempts set status=${input.status},adapter_request_id=${input.adapterRequestId},failure_code=${input.failureCode},completed_at=now() where id=${input.executionId}::uuid returning *`); if(!row.rows[0]) throw new Error('execution attempt not found'); return mapExecutionAttempt(row.rows[0] as Record<string, unknown>);},existingTx); },
  async createOutcome(input: Omit<Outcome,'contractVersion'|'outcomeId'|'recordedAt'>, existingTx?:Tx){const outcome=outcomeSchema.parse({...input,contractVersion:'outcome.v1',outcomeId:randomUUID(),recordedAt:new Date()}); return tenant(db,outcome.organizationId,outcome.businessId,async tx=>{await tx.execute(sql`insert into action_outcomes (id,organization_id,business_id,visitor_identity_id,session_id,decision_id,action_request_id,execution_id,outcome_type,status,evidence_type,evidence_reference,value,occurred_at) values (${outcome.outcomeId}::uuid,${outcome.organizationId}::uuid,${outcome.businessId}::uuid,${outcome.visitorIdentityId}::uuid,${outcome.sessionId}::uuid,${outcome.decisionId}::uuid,${outcome.actionRequestId}::uuid,${outcome.executionId}::uuid,${outcome.outcomeType},${outcome.status},${outcome.evidenceType},${outcome.evidenceReference},${outcome.value===null?null:JSON.stringify(outcome.value)}::jsonb,${outcome.occurredAt})`);return outcome;},existingTx);}
}; }
