import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { conversionDefinitionSchema, conversionFactSchema, type ConversionDefinition, type ConversionFact } from '@kablet/domain';
import type { Database, DatabaseTransaction } from './index.js';

export function createConversionRepository(db: Database['db'], existingTx?: DatabaseTransaction) {
  const run = async <T>(org: string, business: string, fn: (tx: DatabaseTransaction) => Promise<T>) => { const scoped = async (tx: DatabaseTransaction) => { await tx.execute(sql`select set_config('kablet.organization_id',${org},true),set_config('kablet.business_id',${business},true)`); return fn(tx); }; return existingTx ? scoped(existingTx) : db.transaction(scoped); };
  const mapDefinition = (r: Record<string, unknown>): ConversionDefinition => conversionDefinitionSchema.parse({ contractVersion:'conversion-definition.v1', id:r.id, organizationId:r.organization_id, businessId:r.business_id, definitionKey:r.definition_key, definitionVersion:r.definition_version, revisionNumber:Number(r.revision_number), capabilityId:r.capability_id, capabilityVersion:r.capability_version, outcomeType:r.outcome_type, active:r.active, createdAt:r.created_at });
  const mapFact = (r: Record<string, unknown>): ConversionFact => conversionFactSchema.parse({ contractVersion:'conversion-fact.v1', id:r.id, organizationId:r.organization_id, businessId:r.business_id, outcomeId:r.outcome_id, conversionDefinitionId:r.conversion_definition_id, occurredAt:r.occurred_at, classifiedAt:r.classified_at });
  return {
    async createDefinition(input: Omit<ConversionDefinition,'contractVersion'|'createdAt'|'revisionNumber'> & { createdAt?: Date }) { const definition = { ...input, contractVersion:'conversion-definition.v1' as const, revisionNumber:1, createdAt:input.createdAt ?? new Date() }; return run(definition.organizationId,definition.businessId,async tx => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`${definition.organizationId}:${definition.businessId}:${definition.definitionKey}`},0))`); const next=await tx.execute(sql`select coalesce(max(revision_number),0)+1 as revision_number from conversion_definition_revisions where organization_id=${definition.organizationId}::uuid and business_id=${definition.businessId}::uuid and definition_key=${definition.definitionKey}`); definition.revisionNumber=Number(next.rows[0].revision_number); const row=await tx.execute(sql`insert into conversion_definition_revisions(id,organization_id,business_id,definition_key,definition_version,revision_number,capability_id,capability_version,outcome_type,active,created_at) values (${definition.id}::uuid,${definition.organizationId}::uuid,${definition.businessId}::uuid,${definition.definitionKey},${definition.definitionVersion},${definition.revisionNumber},${definition.capabilityId}::uuid,${definition.capabilityVersion},${definition.outcomeType},${definition.active},${definition.createdAt}) returning *`); return mapDefinition(row.rows[0] as Record<string,unknown>); }); },
    async listDefinitions(organizationId:string,businessId:string) { return run(organizationId,businessId,async tx => { const rows=await tx.execute(sql`select distinct on (definition_key) * from conversion_definition_revisions where organization_id=${organizationId}::uuid and business_id=${businessId}::uuid order by definition_key,revision_number desc`); return rows.rows.map(r=>mapDefinition(r as Record<string,unknown>)); }); },
    async classifyVerifiedOutcome(organizationId:string,businessId:string,outcomeId:string) { return run(organizationId,businessId,async tx => { const rows=await tx.execute(sql`select o.id as outcome_id,o.occurred_at,d.id as definition_id from action_outcomes o join action_requests ar on ar.id=o.action_request_id and ar.organization_id=o.organization_id and ar.business_id=o.business_id join (select distinct on (definition_key) * from conversion_definition_revisions where organization_id=${organizationId}::uuid and business_id=${businessId}::uuid order by definition_key,revision_number desc) d on d.organization_id=ar.organization_id and d.business_id=ar.business_id and d.active and d.capability_id=ar.capability_id and d.capability_version=ar.capability_version and d.outcome_type=o.outcome_type where o.id=${outcomeId}::uuid and o.organization_id=${organizationId}::uuid and o.business_id=${businessId}::uuid and o.status='verified'`); const facts: ConversionFact[]=[]; for (const row of rows.rows) { const r=row as Record<string,unknown>; const id=randomUUID(); const inserted=await tx.execute(sql`insert into conversion_facts(id,organization_id,business_id,outcome_id,conversion_definition_id,occurred_at,classified_at) values (${id}::uuid,${organizationId}::uuid,${businessId}::uuid,${r.outcome_id}::uuid,${r.definition_id}::uuid,${r.occurred_at},now()) on conflict (organization_id,business_id,outcome_id,conversion_definition_id) do nothing returning *`); if(inserted.rows[0]) facts.push(mapFact(inserted.rows[0] as Record<string,unknown>)); else { const existing=await tx.execute(sql`select * from conversion_facts where organization_id=${organizationId}::uuid and business_id=${businessId}::uuid and outcome_id=${outcomeId}::uuid and conversion_definition_id=${r.definition_id}::uuid`); if(existing.rows[0]) facts.push(mapFact(existing.rows[0] as Record<string,unknown>)); } } return facts; }); },
    async listFacts(organizationId:string,businessId:string) { return run(organizationId,businessId,async tx => { const rows=await tx.execute(sql`select * from conversion_facts where organization_id=${organizationId}::uuid and business_id=${businessId}::uuid order by occurred_at,id`); return rows.rows.map(r=>mapFact(r as Record<string,unknown>)); }); },
  };
}
