import { sql } from 'drizzle-orm';
import { experienceExposureSchema, interactionFactSchema, type ExperienceExposure, type InteractionFact } from '@kablet/domain';
import type { Database, DatabaseTransaction } from './index.js';

export function createMeasurementRepository(db: Database['db'], existingTx?: DatabaseTransaction) {
  const run = async <T>(organizationId: string, businessId: string, fn: (tx: DatabaseTransaction) => Promise<T>) => {
    const scoped = async (tx: DatabaseTransaction) => { await tx.execute(sql`select set_config('kablet.organization_id',${organizationId},true),set_config('kablet.business_id',${businessId},true)`); return fn(tx); };
    return existingTx ? scoped(existingTx) : db.transaction(scoped);
  };
  return {
    async insertExposure(input: ExperienceExposure) { await run(input.organizationId,input.businessId,async tx => { await tx.execute(sql`select id from interaction_sessions where id=${input.interactionSessionId}::uuid and organization_id=${input.organizationId}::uuid and business_id=${input.businessId}::uuid for update`); const sequence = await tx.execute(sql`select coalesce(max(exposure_sequence),0)+1 as next_sequence from experience_exposures where organization_id=${input.organizationId}::uuid and business_id=${input.businessId}::uuid and interaction_session_id=${input.interactionSessionId}::uuid`); await tx.execute(sql`insert into experience_exposures (id,organization_id,business_id,visitor_identity_id,visitor_session_id,interaction_session_id,decision_id,exposure_sequence,exposure_kind,exposed_at) values (${input.id}::uuid,${input.organizationId}::uuid,${input.businessId}::uuid,${input.visitorIdentityId}::uuid,${input.visitorSessionId}::uuid,${input.interactionSessionId}::uuid,${input.decisionId}::uuid,${sequence.rows[0].next_sequence},${input.exposureKind},${input.exposedAt})`); }); return input.id; },
    async insertFact(input: InteractionFact) { await run(input.organizationId,input.businessId,async tx => { await tx.execute(sql`insert into interaction_facts (id,organization_id,business_id,visitor_identity_id,visitor_session_id,interaction_session_id,decision_id,exposure_id,interaction_kind,occurred_at,idempotency_key,action_request_id) values (${input.id}::uuid,${input.organizationId}::uuid,${input.businessId}::uuid,${input.visitorIdentityId}::uuid,${input.visitorSessionId}::uuid,${input.interactionSessionId}::uuid,${input.decisionId}::uuid,${input.exposureId}::uuid,${input.interactionKind},${input.occurredAt},${input.idempotencyKey},${input.actionRequestId}::uuid) on conflict (organization_id,business_id,interaction_session_id,interaction_kind,idempotency_key) do nothing`); }); },
    async getLatestExposure(organizationId: string, businessId: string, interactionSessionId: string) { return run(organizationId,businessId,async tx => { const r = await tx.execute(sql`select * from experience_exposures where organization_id=${organizationId}::uuid and business_id=${businessId}::uuid and interaction_session_id=${interactionSessionId}::uuid order by exposure_sequence desc limit 1`); const x = r.rows[0] as Record<string, unknown> | undefined; return x ? experienceExposureSchema.parse({ contractVersion:'experience-exposure.v1', id:x.id, organizationId:x.organization_id, businessId:x.business_id, visitorIdentityId:x.visitor_identity_id, visitorSessionId:x.visitor_session_id, interactionSessionId:x.interaction_session_id, decisionId:x.decision_id, exposureKind:x.exposure_kind, exposedAt:x.exposed_at }) : null; }); },
    async getExposure(id: string, organizationId: string, businessId: string) { return run(organizationId,businessId,async tx => { const r = await tx.execute(sql`select * from experience_exposures where id=${id}::uuid`); const x = r.rows[0] as Record<string, unknown> | undefined; return x ? experienceExposureSchema.parse({ contractVersion:'experience-exposure.v1', id:x.id, organizationId:x.organization_id, businessId:x.business_id, visitorIdentityId:x.visitor_identity_id, visitorSessionId:x.visitor_session_id, interactionSessionId:x.interaction_session_id, decisionId:x.decision_id, exposureKind:x.exposure_kind, exposedAt:x.exposed_at }) : null; }); },
    async getFact(id: string, organizationId: string, businessId: string) { return run(organizationId,businessId,async tx => { const r = await tx.execute(sql`select * from interaction_facts where id=${id}::uuid`); const x = r.rows[0] as Record<string, unknown> | undefined; return x ? interactionFactSchema.parse({ contractVersion:'interaction-fact.v1', id:x.id, organizationId:x.organization_id, businessId:x.business_id, visitorIdentityId:x.visitor_identity_id, visitorSessionId:x.visitor_session_id, interactionSessionId:x.interaction_session_id, decisionId:x.decision_id, exposureId:x.exposure_id, interactionKind:x.interaction_kind, occurredAt:x.occurred_at, idempotencyKey:x.idempotency_key, actionRequestId:x.action_request_id }) : null; }); },
  };
}
