import { randomBytes, randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import pg from 'pg';
import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { describe, expect, it } from 'vitest';
import { loadTestManagerConfig } from '@kablet/config';
import { createAttributionRepository, createDb } from '@kablet/db';
import { createInteractionService } from '../../apps/web/lib/interaction-service';
import { seedBaselineIntentPolicy } from './intent-policy-fixture';

const manager = loadTestManagerConfig();
const migrationsFolder = resolve(process.cwd(), 'packages/db/drizzle');
const base = `postgresql://${encodeURIComponent(manager.TEST_MANAGER_USER)}:${encodeURIComponent(manager.TEST_MANAGER_PASSWORD)}@${manager.TEST_MANAGER_HOST}:${manager.TEST_MANAGER_PORT}`;
const bootstrapUser = process.env.TEST_BOOTSTRAP_USER; const bootstrapPassword = process.env.TEST_BOOTSTRAP_PASSWORD; const roleAdminUrl = process.env.TEST_ROLE_ADMIN_URL; const appPassword = process.env.TEST_APP_PASSWORD;
function dbName() { return `kablet_test_${randomBytes(16).toString('hex')}`; }
async function provision() {
  if (!bootstrapUser || !bootstrapPassword || !roleAdminUrl || !appPassword) throw new Error('attribution integration configuration is incomplete');
  const database = dbName(); const managerPool = new pg.Pool({ connectionString: `${base}/postgres`, max: 1 }); let target: pg.Pool | undefined; let bootstrap: ReturnType<typeof createDb> | undefined; let admin: pg.Pool | undefined;
  try {
    await managerPool.query(`create database "${database}" owner "${manager.TEST_MANAGER_USER}"`); await managerPool.query(`grant connect, create on database "${database}" to "${bootstrapUser}"`);
    target = new pg.Pool({ connectionString: `${base}/${database}`, max: 1 }); await target.query(`grant usage, create on schema public to "${bootstrapUser}"`); await target.query('grant usage, create on schema public to kablet_privacy_owner'); await target.end(); target = undefined;
    bootstrap = createDb(`postgresql://${encodeURIComponent(bootstrapUser)}:${encodeURIComponent(bootstrapPassword)}@${manager.TEST_MANAGER_HOST}:${manager.TEST_MANAGER_PORT}/${database}`); admin = new pg.Pool({ connectionString: roleAdminUrl, max: 1 }); await admin.query('grant kablet_privacy_owner to kablet_test_bootstrap with set true, inherit false'); try { await migrate(bootstrap.db, { migrationsFolder }); } finally { await admin.query('revoke kablet_privacy_owner from kablet_test_bootstrap'); }
    await bootstrap.db.execute(sql`grant usage on schema public to kablet_dev`); await bootstrap.db.execute(sql`grant select,insert,update,delete on organizations,businesses,visitor_identities,visitor_sessions,visitor_observations,visitor_state_revisions,visitor_states,visitor_decisions,visitor_decision_business_truth_refs,interaction_sessions,business_offerings,business_offering_revisions,offering_publications,visitor_contact_records,visitor_consents to kablet_dev`); await admin.end(); admin = undefined; await bootstrap.pool.end(); bootstrap = undefined;
    return { database, managerPool, runtime: createDb(`postgresql://kablet_dev:${encodeURIComponent(appPassword)}@${manager.TEST_MANAGER_HOST}:${manager.TEST_MANAGER_PORT}/${database}`) };
  } catch (error) { if (target) await target.end().catch(() => undefined); if (admin) await admin.end().catch(() => undefined); if (bootstrap) await bootstrap.pool.end().catch(() => undefined); await managerPool.query(`drop database if exists "${database}"`).catch(() => undefined); await managerPool.end().catch(() => undefined); throw error; }
}
async function dispose(resource: Awaited<ReturnType<typeof provision>>) { await resource.runtime.pool.end(); await resource.managerPool.query(`drop database "${resource.database}"`); await resource.managerPool.end(); }
async function tenant(resource: Awaited<ReturnType<typeof provision>>) { const organizationId = randomUUID(); const businessId = randomUUID(); await resource.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${organizationId},true),set_config('kablet.business_id',${businessId},true)`); await tx.execute(sql`insert into organizations(id,name) values (${organizationId}::uuid,'Attribution Org')`); await tx.execute(sql`insert into businesses(id,organization_id,name) values (${businessId}::uuid,${organizationId}::uuid,'Attribution Business')`); }); await seedBaselineIntentPolicy(resource.runtime.db, organizationId, businessId); return { organizationId, businessId }; }
async function start(resource: Awaited<ReturnType<typeof provision>>, ids: { organizationId: string; businessId: string }) { const result = await createInteractionService({ db: resource.runtime.db, ...ids }).start(new Date(Date.now() + 3600000)); const row = await resource.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`); return tx.execute(sql`select i.id as interaction_id,e.id as exposure_id,e.decision_id,ac.id as acquisition_id from interaction_sessions i join experience_exposures e on e.interaction_session_id=i.id join acquisition_contexts ac on ac.interaction_session_id=i.id where i.visitor_identity_id=${result.visitorId}::uuid order by e.exposure_sequence desc limit 1`); }); expect(row.rows).toHaveLength(1); return { ...result, interactionId: String(row.rows[0].interaction_id), exposureId: String(row.rows[0].exposure_id), decisionId: String(row.rows[0].decision_id), acquisitionId: String(row.rows[0].acquisition_id) }; }
async function outcomeLineage(resource: Awaited<ReturnType<typeof provision>>, ids: { organizationId: string; businessId: string }, started: Awaited<ReturnType<typeof start>>, options: { acquisition?: boolean; verified?: boolean; fact?: boolean; interactionId?: string } = {}) {
  const acquisitionId = started.acquisitionId; const requestId = randomUUID(); const executionId = randomUUID(); const outcomeId = randomUUID(); const interactionId = options.interactionId ?? started.interactionId;
  await resource.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`); await tx.execute(sql`insert into action_requests(id,organization_id,business_id,visitor_identity_id,session_id,decision_id,capability_id,capability_version,input,idempotency_key,status) values (${requestId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${started.visitorId}::uuid,${started.sessionId}::uuid,${started.decisionId}::uuid,${randomUUID()}::uuid,'1','{}'::jsonb,${randomUUID()},'succeeded')`); if (options.fact) await tx.execute(sql`insert into interaction_facts(id,organization_id,business_id,visitor_identity_id,visitor_session_id,interaction_session_id,decision_id,exposure_id,interaction_kind,occurred_at,idempotency_key,action_request_id) values (${randomUUID()}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${started.visitorId}::uuid,${started.sessionId}::uuid,${interactionId}::uuid,${started.decisionId}::uuid,${started.exposureId}::uuid,'action_confirmed',now(),${randomUUID()},${requestId}::uuid)`); await tx.execute(sql`insert into execution_attempts(id,organization_id,business_id,action_request_id,attempt_number,status,external_operation_id) values (${executionId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${requestId}::uuid,1,'succeeded',${`kablet:${requestId}`})`); await tx.execute(sql`insert into action_outcomes(id,organization_id,business_id,visitor_identity_id,session_id,decision_id,action_request_id,execution_id,outcome_type,status,evidence_type,evidence_reference,occurred_at) values (${outcomeId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${started.visitorId}::uuid,${started.sessionId}::uuid,${started.decisionId}::uuid,${requestId}::uuid,${executionId}::uuid,'lead.delivered',${options.verified === false ? 'rejected' : 'verified'},'test','test',now())`); });
  return { outcomeId, acquisitionId, requestId };
}

describe('03C attribution PostgreSQL integration', () => {
  it('attributes only verified canonical same-session lineage and is idempotent', async () => { const r = await provision(); try { const ids = await tenant(r); const s = await start(r, ids); const lineage = await outcomeLineage(r, ids, s, { acquisition: true, verified: true, fact: true }); const repo = createAttributionRepository(r.runtime.db); const first = await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, lineage.outcomeId); const second = await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, lineage.outcomeId); expect(first).toMatchObject({ outcomeId: lineage.outcomeId, acquisitionContextId: lineage.acquisitionId, interactionSessionId: s.interactionId, rule: 'same_interaction_acquisition.v1' }); expect(second?.id).toBe(first?.id); const rows = await r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`); return tx.execute(sql`select count(*)::int as count from outcome_attributions`); }); expect(rows.rows[0].count).toBe(1); } finally { await dispose(r); } }, 90000);
  it('requires the verified Outcome and complete action-confirmation chain', async () => { const r = await provision(); try { const ids = await tenant(r); const s = await start(r, ids); const noFact = await outcomeLineage(r, ids, s, { acquisition: true, verified: true, fact: false }); const rejected = await outcomeLineage(r, ids, s, { acquisition: true, verified: false, fact: true }); const repo = createAttributionRepository(r.runtime.db); expect(await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, noFact.outcomeId)).toBeNull(); expect(await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, rejected.outcomeId)).toBeNull(); } finally { await dispose(r); } }, 90000);
  it('does not fall back across interaction sessions', async () => { const r = await provision(); try { const ids = await tenant(r); const a = await start(r, ids); const aOutcome = await outcomeLineage(r, ids, a, { acquisition: true, verified: true, fact: true }); const b = await start(r, ids); const bOutcome = await outcomeLineage(r, ids, b, { acquisition: false, verified: true, fact: true }); const repo = createAttributionRepository(r.runtime.db); await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, aOutcome.outcomeId); const attributed = await repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, bOutcome.outcomeId); expect(attributed?.acquisitionContextId).toBe(b.acquisitionId); expect(attributed?.acquisitionContextId).not.toBe(a.acquisitionId); } finally { await dispose(r); } }, 90000);
  it('converges concurrent attribution attempts at the database uniqueness boundary', async () => { const r = await provision(); try { const ids = await tenant(r); const s = await start(r, ids); const lineage = await outcomeLineage(r, ids, s, { acquisition: true, verified: true, fact: true }); const repo = createAttributionRepository(r.runtime.db); const results = await Promise.all([1,2,3].map(() => repo.attributeVerifiedOutcome(ids.organizationId, ids.businessId, lineage.outcomeId))); expect(new Set(results.filter(Boolean).map(item => item!.id)).size).toBe(1); } finally { await dispose(r); } }, 90000);
  it('enforces runtime immutability, RLS isolation, and privacy deletion', async () => { const r = await provision(); try { const a = await tenant(r); const b = await tenant(r); const s = await start(r, a); const lineage = await outcomeLineage(r, a, s, { acquisition: true, verified: true, fact: true }); const repo = createAttributionRepository(r.runtime.db); await repo.attributeVerifiedOutcome(a.organizationId, a.businessId, lineage.outcomeId); const read = (ids: { organizationId: string; businessId: string }) => r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`); return tx.execute(sql`select * from outcome_attributions where outcome_id=${lineage.outcomeId}::uuid`); }); expect((await read(a)).rows).toHaveLength(1); expect((await read(b)).rows).toHaveLength(0); expect((await r.runtime.db.execute(sql`select id from outcome_attributions`)).rows).toHaveLength(0); await expect(r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${a.organizationId},true),set_config('kablet.business_id',${a.businessId},true)`); await tx.execute(sql`update outcome_attributions set rule='bad' where outcome_id=${lineage.outcomeId}::uuid`); })).rejects.toThrow(); await expect(r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${a.organizationId},true),set_config('kablet.business_id',${a.businessId},true)`); await tx.execute(sql`delete from outcome_attributions where outcome_id=${lineage.outcomeId}::uuid`); })).rejects.toMatchObject({ cause: { code: '42501' } }); await r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${a.organizationId},true),set_config('kablet.business_id',${a.businessId},true)`); await tx.execute(sql`select public.kablet_visitor_privacy_delete(${a.organizationId}::uuid,${s.visitorId}::uuid)`); }); expect((await read(a)).rows).toHaveLength(0); } finally { await dispose(r); } }, 90000);
  it('rejects cross-tenant attribution lineage and stores no acquisition payload', async () => { const r = await provision(); try { const a = await tenant(r); const b = await tenant(r); const s = await start(r, a); const lineage = await outcomeLineage(r, a, s, { acquisition: true, verified: true, fact: true }); const repo = createAttributionRepository(r.runtime.db); await repo.attributeVerifiedOutcome(a.organizationId, a.businessId, lineage.outcomeId); await expect(r.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${b.organizationId},true),set_config('kablet.business_id',${b.businessId},true)`); await tx.execute(sql`insert into outcome_attributions(id,organization_id,business_id,outcome_id,acquisition_context_id,interaction_session_id,rule,attributed_at) values (${randomUUID()}::uuid,${b.organizationId}::uuid,${b.businessId}::uuid,${lineage.outcomeId}::uuid,${lineage.acquisitionId}::uuid,${s.interactionId}::uuid,'same_interaction_acquisition.v1',now())`); })).rejects.toThrow(); const row = await readAttribution(r, a, lineage.outcomeId); expect(JSON.stringify(row.rows[0])).not.toContain('campaign'); expect(JSON.stringify(row.rows[0])).not.toContain('landing'); } finally { await dispose(r); } }, 90000);
});
async function readAttribution(resource: Awaited<ReturnType<typeof provision>>, ids: { organizationId: string; businessId: string }, outcomeId: string) { return resource.runtime.db.transaction(async tx => { await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`); return tx.execute(sql`select * from outcome_attributions where outcome_id=${outcomeId}::uuid`); }); }
