import { randomBytes, randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import pg from 'pg';
import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { describe, expect, it } from 'vitest';
import { loadTestManagerConfig } from '@kablet/config';
import { createConversionRepository, createDb } from '@kablet/db';
import { createInteractionService } from '../../apps/web/lib/interaction-service';

const m=loadTestManagerConfig(); const folder=resolve(process.cwd(),'packages/db/drizzle'); const base=`postgresql://${encodeURIComponent(m.TEST_MANAGER_USER)}:${encodeURIComponent(m.TEST_MANAGER_PASSWORD)}@${m.TEST_MANAGER_HOST}:${m.TEST_MANAGER_PORT}`; const bu=process.env.TEST_BOOTSTRAP_USER; const bp=process.env.TEST_BOOTSTRAP_PASSWORD; const adminUrl=process.env.TEST_ROLE_ADMIN_URL; const appPassword=process.env.TEST_APP_PASSWORD;
function name(){return `kablet_test_${randomBytes(16).toString('hex')}`;}
async function provision(){if(!bu||!bp||!adminUrl||!appPassword)throw new Error('conversion integration configuration is incomplete');const database=name(),manager=new pg.Pool({connectionString:`${base}/postgres`,max:1});let target:pg.Pool|undefined,boot:ReturnType<typeof createDb>|undefined,admin:pg.Pool|undefined;try{await manager.query(`create database "${database}" owner "${m.TEST_MANAGER_USER}"`);await manager.query(`grant connect,create on database "${database}" to "${bu}"`);target=new pg.Pool({connectionString:`${base}/${database}`,max:1});await target.query(`grant usage,create on schema public to "${bu}"`);await target.query('grant usage,create on schema public to kablet_privacy_owner');await target.end();target=undefined;boot=createDb(`postgresql://${encodeURIComponent(bu)}:${encodeURIComponent(bp)}@${m.TEST_MANAGER_HOST}:${m.TEST_MANAGER_PORT}/${database}`);admin=new pg.Pool({connectionString:adminUrl,max:1});await admin.query('grant kablet_privacy_owner to kablet_test_bootstrap with set true, inherit false');try{await migrate(boot.db,{migrationsFolder:folder});}finally{await admin.query('revoke kablet_privacy_owner from kablet_test_bootstrap')}await boot.db.execute(sql`grant usage on schema public to kablet_dev`);await boot.db.execute(sql`grant select,insert,update,delete on organizations,businesses,visitor_identities,visitor_sessions,visitor_observations,visitor_state_revisions,visitor_states,visitor_decisions,visitor_decision_business_truth_refs,interaction_sessions,business_offerings,business_offering_revisions,offering_publications,visitor_contact_records,visitor_consents to kablet_dev`);await admin.end();admin=undefined;await boot.pool.end();boot=undefined;return{database,manager,runtime:createDb(`postgresql://kablet_dev:${encodeURIComponent(appPassword)}@${m.TEST_MANAGER_HOST}:${m.TEST_MANAGER_PORT}/${database}`)}}catch(e){if(target)await target.end().catch(()=>undefined);if(admin)await admin.end().catch(()=>undefined);if(boot)await boot.pool.end().catch(()=>undefined);await manager.query(`drop database if exists "${database}"`).catch(()=>undefined);await manager.end().catch(()=>undefined);throw e}}
async function dispose(r:Awaited<ReturnType<typeof provision>>){await r.runtime.pool.end();await r.manager.query(`drop database "${r.database}"`);await r.manager.end()}
async function tenant(r:Awaited<ReturnType<typeof provision>>){const organizationId=randomUUID(),businessId=randomUUID();await r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${organizationId},true),set_config('kablet.business_id',${businessId},true)`);await tx.execute(sql`insert into organizations(id,name)values(${organizationId}::uuid,'Conversion Org')`);await tx.execute(sql`insert into businesses(id,organization_id,name)values(${businessId}::uuid,${organizationId}::uuid,'Conversion Business')`)});return{organizationId,businessId}}
async function lineage(r:Awaited<ReturnType<typeof provision>>,ids:{organizationId:string;businessId:string},outcomeType='lead.delivered',status='verified'){const started=await createInteractionService({db:r.runtime.db,...ids}).start(new Date(Date.now()+3600000));const row=await r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`);return tx.execute(sql`select i.id interaction_id,e.id exposure_id,e.decision_id from interaction_sessions i join experience_exposures e on e.interaction_session_id=i.id where i.visitor_identity_id=${started.visitorId}::uuid`)});const x=row.rows[0],requestId=randomUUID(),executionId=randomUUID(),outcomeId=randomUUID();await r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`);await tx.execute(sql`insert into action_requests(id,organization_id,business_id,visitor_identity_id,session_id,decision_id,capability_id,capability_version,input,idempotency_key,status)values(${requestId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${started.visitorId}::uuid,${started.sessionId}::uuid,${x.decision_id}::uuid,'d4000000-0000-4000-8000-000000000004','1','{}'::jsonb,${randomUUID()},'succeeded')`);await tx.execute(sql`insert into execution_attempts(id,organization_id,business_id,action_request_id,attempt_number,status,external_operation_id)values(${executionId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${requestId}::uuid,1,'succeeded',${requestId})`);await tx.execute(sql`insert into action_outcomes(id,organization_id,business_id,visitor_identity_id,session_id,decision_id,action_request_id,execution_id,outcome_type,status,evidence_type,evidence_reference,occurred_at)values(${outcomeId}::uuid,${ids.organizationId}::uuid,${ids.businessId}::uuid,${started.visitorId}::uuid,${started.sessionId}::uuid,${x.decision_id}::uuid,${requestId}::uuid,${executionId}::uuid,${outcomeType},${status},'test','test',${new Date('2026-01-01T00:00:00Z')})`)});return{...started,interactionId:String(x.interaction_id),exposureId:String(x.exposure_id),decisionId:String(x.decision_id),outcomeId}}
async function definition(r:Awaited<ReturnType<typeof provision>>,ids:{organizationId:string;businessId:string},key='lead',version='v1',active=true,capabilityId='d4000000-0000-4000-8000-000000000004',createdAt?:Date){return createConversionRepository(r.runtime.db).createDefinition({id:randomUUID(),organizationId:ids.organizationId,businessId:ids.businessId,definitionKey:key,definitionVersion:version,capabilityId,capabilityVersion:'1',outcomeType:'lead.delivered',active,createdAt})}
async function count(r:Awaited<ReturnType<typeof provision>>,ids:{organizationId:string;businessId:string}){return r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${ids.organizationId},true),set_config('kablet.business_id',${ids.businessId},true)`);return tx.execute(sql`select * from conversion_facts`)})}

describe('03D conversion PostgreSQL integration',()=>{
it('classifies only verified matching Outcomes and preserves occurredAt',async()=>{const r=await provision();try{const ids=await tenant(r);await definition(r,ids);const s=await lineage(r,ids);const facts=await createConversionRepository(r.runtime.db).classifyVerifiedOutcome(ids.organizationId,ids.businessId,s.outcomeId);expect(facts).toHaveLength(1);expect(facts[0]).toMatchObject({outcomeId:s.outcomeId,conversionDefinitionId:expect.any(String),occurredAt:new Date('2026-01-01T00:00:00Z')});}finally{await dispose(r)}},90000);
it('rejects pending, rejected, and mismatched durable Outcomes',async()=>{const r=await provision();try{const ids=await tenant(r);await definition(r,ids);const repo=createConversionRepository(r.runtime.db);for(const status of ['pending','rejected']){const s=await lineage(r,ids,'lead.delivered',status);expect(await repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,s.outcomeId)).toHaveLength(0)}const mismatch=await lineage(r,ids,'other.outcome','verified');expect(await repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,mismatch.outcomeId)).toHaveLength(0);}finally{await dispose(r)}},90000);
it('uses immutable newest-revision lifecycle and permits multiple matching definitions',async()=>{const r=await provision();try{const ids=await tenant(r);const v1=await definition(r,ids,'lead','v1',true);expect(v1.revisionNumber).toBe(1);const s1=await lineage(r,ids);const repo=createConversionRepository(r.runtime.db);expect(await repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,s1.outcomeId)).toHaveLength(1);const v2=await definition(r,ids,'lead','v2',false);expect(v2.revisionNumber).toBe(2);const s2=await lineage(r,ids);expect(await repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,s2.outcomeId)).toHaveLength(0);const other=await definition(r,ids,'secondary','v1',true);expect(other.revisionNumber).toBe(1);const s3=await lineage(r,ids);expect(await repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,s3.outcomeId)).toHaveLength(1);const historical=await repo.listFacts(ids.organizationId,ids.businessId);expect(historical).toEqual(expect.arrayContaining([expect.objectContaining({outcomeId:s1.outcomeId,conversionDefinitionId:v1.id})]));expect(other.id).not.toBe(v2.id);}finally{await dispose(r)}},90000);
it('is idempotent and converges under concurrency',async()=>{const r=await provision();try{const ids=await tenant(r);await definition(r,ids);const s=await lineage(r,ids);const repo=createConversionRepository(r.runtime.db);const all=await Promise.all([1,2,3].map(()=>repo.classifyVerifiedOutcome(ids.organizationId,ids.businessId,s.outcomeId)));const durable=(await count(r,ids)).rows;expect(durable).toHaveLength(1);expect(all.some(x=>x.length===1)).toBe(true);expect(new Set(all.flat().map(x=>x.id))).toEqual(new Set([String(durable[0].id)]));}finally{await dispose(r)}},90000);
it('allocates concurrent revisions monotonically and independently per definition key',async()=>{const r=await provision();try{const ids=await tenant(r);const repo=createConversionRepository(r.runtime.db);const revisions=await Promise.all([definition(r,ids,'parallel','v1',true),definition(r,ids,'parallel','v2',false)]);expect(new Set(revisions.map(x=>x.revisionNumber))).toEqual(new Set([1,2]));const independent=await definition(r,ids,'independent','v1',true);expect(independent.revisionNumber).toBe(1);const listed=await repo.listDefinitions(ids.organizationId,ids.businessId);expect(listed.find(x=>x.definitionKey==='parallel')?.revisionNumber).toBe(2);}finally{await dispose(r)}},90000);
it('uses revision numbers when createdAt values tie',async()=>{const r=await provision();try{const ids=await tenant(r);const tied=new Date('2026-01-01T00:00:00.000Z');const first=await definition(r,ids,'tied','v1',true,undefined,tied);const second=await definition(r,ids,'tied','v2',false,undefined,tied);expect(first.revisionNumber).toBe(1);expect(second.revisionNumber).toBe(2);const s=await lineage(r,ids);expect(await createConversionRepository(r.runtime.db).classifyVerifiedOutcome(ids.organizationId,ids.businessId,s.outcomeId)).toHaveLength(0);}finally{await dispose(r)}},90000);
it('keeps definitions tenant-scoped and facts immutable/privacy-deletable',async()=>{const r=await provision();try{const a=await tenant(r),b=await tenant(r);await definition(r,a);const s=await lineage(r,a);await createConversionRepository(r.runtime.db).classifyVerifiedOutcome(a.organizationId,a.businessId,s.outcomeId);expect((await count(r,a)).rows).toHaveLength(1);expect((await count(r,b)).rows).toHaveLength(0);await expect(r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${a.organizationId},true),set_config('kablet.business_id',${a.businessId},true)`);await tx.execute(sql`update conversion_facts set occurred_at=now()`)})).rejects.toThrow();await expect(r.runtime.db.transaction(async tx=>{await tx.execute(sql`select set_config('kablet.organization_id',${a.organizationId},true),set_config('kablet.business_id',${a.businessId},true)`);return tx.execute(sql`select public.kablet_visitor_privacy_delete(${a.organizationId}::uuid,${s.visitorId}::uuid)`)})).resolves.toBeDefined();expect((await count(r,a)).rows).toHaveLength(0);const defs=await createConversionRepository(r.runtime.db).listDefinitions(a.organizationId,a.businessId);expect(defs.length).toBeGreaterThan(0);}finally{await dispose(r)}},90000);
});
