import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';
import pg from 'pg';
import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb } from '@kablet/db';
import { loadTestManagerConfig } from '@kablet/config';
import { describe, expect, it } from 'vitest';

const migrationsFolder = resolve(process.cwd(), 'packages/db/drizzle');
const manager = loadTestManagerConfig();
const managerConnection = `postgresql://${encodeURIComponent(manager.TEST_MANAGER_USER)}:${encodeURIComponent(manager.TEST_MANAGER_PASSWORD)}@${manager.TEST_MANAGER_HOST}:${manager.TEST_MANAGER_PORT}/${manager.TEST_MANAGER_DATABASE}`;
function databaseName() { return `kablet_test_${randomBytes(16).toString('hex')}`; }
async function provision() { const managerPool = new pg.Pool({ connectionString: managerConnection, max: 1 }); const identity = await managerPool.query('select current_user, current_database(), version()'); if (identity.rows[0].current_user !== 'kablet_test_manager' || identity.rows[0].current_database !== 'postgres') throw new Error('Unsafe test-manager identity or database'); const name = databaseName(); await managerPool.query(`CREATE DATABASE "${name}" OWNER "kablet_test_manager"`); return {name, url:`postgresql://${encodeURIComponent(manager.TEST_MANAGER_USER)}:${encodeURIComponent(manager.TEST_MANAGER_PASSWORD)}@${manager.TEST_MANAGER_HOST}:${manager.TEST_MANAGER_PORT}/${name}`, managerPool}; }
async function dispose(resource: {name:string; url:string; managerPool:pg.Pool}) { const check = await resource.managerPool.query('select current_user, current_database()'); if (check.rows[0].current_user !== 'kablet_test_manager' || check.rows[0].current_database !== 'postgres') throw new Error('Unsafe cleanup identity'); const target = new pg.Pool({connectionString:resource.url, max:1}); const owner = await target.query('select current_database(), current_user'); await target.end(); if (owner.rows[0].current_database !== resource.name || owner.rows[0].current_user !== 'kablet_test_manager') throw new Error('Unsafe cleanup target'); await resource.managerPool.query(`DROP DATABASE "${resource.name}"`); await resource.managerPool.end(); }
describe('disposable PostgreSQL integration', () => { it('migrates, verifies transactions, and isolates databases', async () => { let first: Awaited<ReturnType<typeof provision>> | undefined; let second: Awaited<ReturnType<typeof provision>> | undefined; try { first = await provision(); second = await provision(); for (const resource of [first, second]) { const {db,pool} = createDb(resource.url); await migrate(db,{migrationsFolder}); await migrate(db,{migrationsFolder}); const inserted = await db.execute(sql`insert into infrastructure_ledger default values returning id`); expect(inserted.rows).toHaveLength(1); const read = await db.execute(sql`select id from infrastructure_ledger`); expect(read.rows).toHaveLength(1); await expect(db.transaction(async tx => { await tx.execute(sql`insert into infrastructure_ledger default values`); throw new Error('rollback-check'); })).rejects.toThrow('rollback-check'); const afterRollback = await db.execute(sql`select id from infrastructure_ledger`); expect(afterRollback.rows).toHaveLength(1); await pool.end(); } const isolated = createDb(first.url); const other = await isolated.db.execute(sql`select count(*)::int as count from infrastructure_ledger`); expect(other.rows[0].count).toBe(1); await isolated.pool.end(); } finally { if (second) await dispose(second); if (first) await dispose(first); } }, 30000); });
