CREATE TABLE IF NOT EXISTS experience_exposures (id uuid PRIMARY KEY, organization_id uuid NOT NULL, business_id uuid NOT NULL, visitor_identity_id uuid NOT NULL, visitor_session_id uuid NOT NULL, interaction_session_id uuid NOT NULL, decision_id uuid NOT NULL, exposure_sequence bigint NOT NULL, exposure_kind varchar(32) NOT NULL CHECK (exposure_kind='server_response'), exposed_at timestamptz NOT NULL, UNIQUE (organization_id,business_id,id), UNIQUE (organization_id,business_id,interaction_session_id,exposure_sequence), FOREIGN KEY (organization_id,business_id,visitor_identity_id) REFERENCES visitor_identities(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,visitor_session_id) REFERENCES visitor_sessions(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,interaction_session_id) REFERENCES interaction_sessions(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,decision_id) REFERENCES visitor_decisions(organization_id,business_id,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS interaction_facts (id uuid PRIMARY KEY, organization_id uuid NOT NULL, business_id uuid NOT NULL, visitor_identity_id uuid NOT NULL, visitor_session_id uuid NOT NULL, interaction_session_id uuid NOT NULL, decision_id uuid NOT NULL, exposure_id uuid NOT NULL, interaction_kind varchar(32) NOT NULL CHECK (interaction_kind IN ('intent_expressed','qualification_answered','contact_submitted','consent_granted','action_confirmed')), occurred_at timestamptz NOT NULL, idempotency_key varchar(200) NOT NULL, action_request_id uuid, UNIQUE (organization_id,business_id,id), UNIQUE (organization_id,business_id,interaction_session_id,interaction_kind,idempotency_key), FOREIGN KEY (organization_id,business_id,visitor_identity_id) REFERENCES visitor_identities(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,visitor_session_id) REFERENCES visitor_sessions(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,interaction_session_id) REFERENCES interaction_sessions(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,decision_id) REFERENCES visitor_decisions(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,exposure_id) REFERENCES experience_exposures(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,action_request_id) REFERENCES action_requests(organization_id,business_id,id) ON DELETE CASCADE);
ALTER TABLE experience_exposures ENABLE ROW LEVEL SECURITY; ALTER TABLE experience_exposures FORCE ROW LEVEL SECURITY;
ALTER TABLE interaction_facts ENABLE ROW LEVEL SECURITY; ALTER TABLE interaction_facts FORCE ROW LEVEL SECURITY;
CREATE POLICY experience_exposure_isolation ON experience_exposures USING (organization_id=kablet_current_org() AND business_id=kablet_current_business()) WITH CHECK (organization_id=kablet_current_org() AND business_id=kablet_current_business());
CREATE POLICY interaction_fact_isolation ON interaction_facts USING (organization_id=kablet_current_org() AND business_id=kablet_current_business()) WITH CHECK (organization_id=kablet_current_org() AND business_id=kablet_current_business());
GRANT SELECT, INSERT ON experience_exposures, interaction_facts TO kablet_dev;
GRANT SELECT, DELETE ON experience_exposures, interaction_facts TO kablet_privacy_owner;
CREATE INDEX experience_exposures_session_idx ON experience_exposures (organization_id,business_id,interaction_session_id,exposed_at);
CREATE INDEX interaction_facts_visitor_idx ON interaction_facts (organization_id,business_id,visitor_identity_id,occurred_at);
CREATE INDEX interaction_facts_decision_idx ON interaction_facts (organization_id,business_id,decision_id,occurred_at);
SET LOCAL ROLE kablet_privacy_owner;
GRANT EXECUTE ON FUNCTION kablet_visitor_immutable() TO kablet_test_bootstrap;
RESET ROLE;
CREATE TRIGGER experience_exposures_immutable BEFORE UPDATE OR DELETE ON experience_exposures FOR EACH ROW EXECUTE FUNCTION kablet_visitor_immutable();
CREATE TRIGGER interaction_facts_immutable BEFORE UPDATE OR DELETE ON interaction_facts FOR EACH ROW EXECUTE FUNCTION kablet_visitor_immutable();
SET LOCAL ROLE kablet_privacy_owner;
REVOKE EXECUTE ON FUNCTION kablet_visitor_immutable() FROM kablet_test_bootstrap;
RESET ROLE;
SET LOCAL ROLE kablet_privacy_owner;
CREATE OR REPLACE FUNCTION kablet_visitor_privacy_delete(p_organization_id uuid, p_visitor_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE deleted boolean;
BEGIN
  IF p_organization_id <> public.kablet_current_org() THEN RAISE EXCEPTION 'privacy tenant mismatch'; END IF;
  INSERT INTO public.kablet_privacy_operations(transaction_id,organization_id,visitor_identity_id) VALUES (pg_catalog.txid_current(),p_organization_id,p_visitor_id);
  DELETE FROM public.interaction_facts WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.experience_exposures WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.acquisition_contexts WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.action_outcomes WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.execution_attempts WHERE organization_id=p_organization_id AND action_request_id IN (SELECT id FROM public.action_requests WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id);
  DELETE FROM public.action_requests WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_decision_business_truth_refs r USING public.visitor_decisions d WHERE d.id=r.decision_id AND d.organization_id=p_organization_id AND d.visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_decisions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_consents WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_contact_records WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.interaction_sessions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_states WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_observations WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_state_revisions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_sessions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_identities WHERE organization_id=p_organization_id AND id=p_visitor_id RETURNING true INTO deleted;
  DELETE FROM public.kablet_privacy_operations WHERE transaction_id=pg_catalog.txid_current() AND organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  RETURN COALESCE(deleted,false);
END $$;
RESET ROLE;
