CREATE TABLE IF NOT EXISTS conversion_definition_revisions (id uuid PRIMARY KEY, organization_id uuid NOT NULL, business_id uuid NOT NULL, definition_key varchar(100) NOT NULL, definition_version varchar(64) NOT NULL, revision_number integer NOT NULL CHECK (revision_number > 0), capability_id uuid NOT NULL, capability_version varchar(64) NOT NULL, outcome_type varchar(100) NOT NULL, active boolean NOT NULL, created_at timestamptz NOT NULL, UNIQUE (organization_id,business_id,id), UNIQUE (organization_id,business_id,definition_key,definition_version), UNIQUE (organization_id,business_id,definition_key,revision_number));
CREATE TABLE IF NOT EXISTS conversion_facts (id uuid PRIMARY KEY, organization_id uuid NOT NULL, business_id uuid NOT NULL, outcome_id uuid NOT NULL, conversion_definition_id uuid NOT NULL, occurred_at timestamptz NOT NULL, classified_at timestamptz NOT NULL, UNIQUE (organization_id,business_id,id), UNIQUE (organization_id,business_id,outcome_id,conversion_definition_id), FOREIGN KEY (organization_id,business_id,outcome_id) REFERENCES action_outcomes(organization_id,business_id,id) ON DELETE CASCADE, FOREIGN KEY (organization_id,business_id,conversion_definition_id) REFERENCES conversion_definition_revisions(organization_id,business_id,id) ON DELETE RESTRICT);
ALTER TABLE conversion_definition_revisions ENABLE ROW LEVEL SECURITY; ALTER TABLE conversion_definition_revisions FORCE ROW LEVEL SECURITY;
ALTER TABLE conversion_facts ENABLE ROW LEVEL SECURITY; ALTER TABLE conversion_facts FORCE ROW LEVEL SECURITY;
CREATE POLICY conversion_definition_isolation ON conversion_definition_revisions USING (organization_id=kablet_current_org() AND business_id=kablet_current_business()) WITH CHECK (organization_id=kablet_current_org() AND business_id=kablet_current_business());
CREATE POLICY conversion_fact_isolation ON conversion_facts USING (organization_id=kablet_current_org() AND business_id=kablet_current_business()) WITH CHECK (organization_id=kablet_current_org() AND business_id=kablet_current_business());
GRANT SELECT, INSERT ON conversion_definition_revisions TO kablet_dev;
GRANT SELECT, INSERT ON conversion_facts TO kablet_dev;
GRANT SELECT, DELETE ON conversion_facts TO kablet_privacy_owner;
CREATE INDEX conversion_facts_definition_idx ON conversion_facts (organization_id,business_id,conversion_definition_id,occurred_at);
SET LOCAL ROLE kablet_privacy_owner;
CREATE OR REPLACE FUNCTION kablet_conversion_definition_immutable() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'conversion definition revision is immutable'; END $$;
CREATE OR REPLACE FUNCTION kablet_conversion_fact_immutable() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
  IF TG_OP='DELETE' AND current_user=pg_get_userbyid((SELECT proowner FROM pg_proc WHERE oid='kablet_visitor_privacy_delete(uuid,uuid)'::regprocedure)) AND EXISTS (SELECT 1 FROM public.action_outcomes o JOIN public.action_requests ar ON ar.id=o.action_request_id AND ar.organization_id=o.organization_id AND ar.business_id=o.business_id JOIN public.kablet_privacy_operations po ON po.transaction_id=pg_catalog.txid_current() AND po.organization_id=OLD.organization_id AND po.visitor_identity_id=ar.visitor_identity_id WHERE o.organization_id=OLD.organization_id AND o.business_id=OLD.business_id AND o.id=OLD.outcome_id) THEN RETURN OLD; END IF;
  RAISE EXCEPTION 'conversion fact is immutable';
END $$;
GRANT EXECUTE ON FUNCTION kablet_conversion_definition_immutable() TO kablet_test_bootstrap;
GRANT EXECUTE ON FUNCTION kablet_conversion_fact_immutable() TO kablet_test_bootstrap;
RESET ROLE;
CREATE TRIGGER conversion_definitions_immutable BEFORE UPDATE OR DELETE ON conversion_definition_revisions FOR EACH ROW EXECUTE FUNCTION kablet_conversion_definition_immutable();
CREATE TRIGGER conversion_facts_immutable BEFORE UPDATE OR DELETE ON conversion_facts FOR EACH ROW EXECUTE FUNCTION kablet_conversion_fact_immutable();
SET LOCAL ROLE kablet_privacy_owner;
REVOKE EXECUTE ON FUNCTION kablet_conversion_definition_immutable() FROM PUBLIC,kablet_test_bootstrap;
REVOKE EXECUTE ON FUNCTION kablet_conversion_fact_immutable() FROM PUBLIC,kablet_test_bootstrap;
RESET ROLE;
SET LOCAL ROLE kablet_privacy_owner;
CREATE OR REPLACE FUNCTION kablet_visitor_privacy_delete(p_organization_id uuid, p_visitor_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE deleted boolean;
BEGIN
  IF p_organization_id <> public.kablet_current_org() THEN RAISE EXCEPTION 'privacy tenant mismatch'; END IF;
  INSERT INTO public.kablet_privacy_operations(transaction_id,organization_id,visitor_identity_id) VALUES (pg_catalog.txid_current(),p_organization_id,p_visitor_id);
  DELETE FROM public.conversion_facts WHERE organization_id=p_organization_id AND outcome_id IN (SELECT o.id FROM public.action_outcomes o JOIN public.action_requests ar ON ar.id=o.action_request_id AND ar.organization_id=o.organization_id AND ar.business_id=o.business_id WHERE o.organization_id=p_organization_id AND ar.visitor_identity_id=p_visitor_id);
  DELETE FROM public.outcome_attributions WHERE organization_id=p_organization_id AND acquisition_context_id IN (SELECT id FROM public.acquisition_contexts WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id);
  DELETE FROM public.interaction_facts WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.experience_exposures WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.acquisition_contexts WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.action_outcomes WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.execution_attempts WHERE organization_id=p_organization_id AND action_request_id IN (SELECT id FROM public.action_requests WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id);
  DELETE FROM public.action_requests WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_decision_business_truth_refs r USING public.visitor_decisions d WHERE d.id=r.decision_id AND d.organization_id=p_organization_id AND d.visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_decisions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_consents WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_contact_records WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.interaction_sessions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_states WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_observations WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_state_revisions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_sessions WHERE organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  DELETE FROM public.visitor_identities WHERE organization_id=p_organization_id AND id=p_visitor_id RETURNING true INTO deleted;
  DELETE FROM public.kablet_privacy_operations WHERE transaction_id=pg_catalog.txid_current() AND organization_id=p_organization_id AND visitor_identity_id=p_visitor_id;
  RETURN COALESCE(deleted,false);
END $$;
RESET ROLE;
